### ISSUE TITLE
Mejorar texto de la web

### ISSUE THREAD

**Issue by ergl** [LibreLabUCM/librelabucm.github.io#3]
Bueno, ahora que ha pasado todo un poco, creo que sería bueno pensar en algo mejor que poner como introducción en la web.

Tenéis alguno una idea, o lo decidimos en alguna reunión que hagamos?

**Comment by Akronix** [comment]
A ver la idea yo creo que va por hay, pero tiene que quedar claro de qué va la aso, qué rollo tenemos y, sobretodo, que den ganas a meterse. Todo eso en un par de párrafos como máximo.
Aprovecho para decir que la web servirá para ir poniendo todo lo que hagamos, así que se pueden ir añadiendo secciones y/o un botón de entrar.
