### ISSUE TITLE
Javascript required to see activities

### ISSUE THREAD

**Issue by ergl** [LibreLabUCM/librelabucm.github.io#8]
Why?
Introduced by b2b7a68

**Comment by Akronix** [comment]
Parece ser que las actividades están en un archivo en formato JSON, webdata.json, y que se cargan con un [`onLoad()`](https://github.com/LibreLabUCM/librelabucm.github.io/commit/b2b7a68baae039c36577939f7a3b25215bc75cca#diff-819f5bf2f62a3d4755d9c369ad054d83R16).

Supongo que no hay muchas alternativas a esto si toda la lógica tiene que estar en el cliente en los github.io.

**Comment by ergl** [comment]
why not just write the content in the html?

**Comment by Akronix** [comment]
@ergl Supongo que únicamente sería más feo y tedioso de editar.
Si nadie opina lo contrario, puedes hacer un PR y lo cambiamos.

**Comment by jesusjda** [comment]
@Akronix Está hecho así justo por ese motivo asiq yo no lo cambiaría dado que añadir actividades y editarlas ahora es mucho más ágil, de todos modos... Se esta empezando la nueva web por lo q no merece la pena cambiar nada ya.

**Comment by ergl** [comment]
Yes, I just wanted to rant a bit :) — we can close this for now
